/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sustainability;

/**
 *
 * @author wikto
 */
import java.util.ArrayList;

public class SustainabilityGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SustainabilityGUI.class.getName());
    BusService B = new BusService();
    IrishRail IR = new IrishRail();
    Luas L = new Luas();
    protected String userEmis;

    /**
     * Creates new form SustainabilityGUI
     */
    public SustainabilityGUI() {
        initComponents();
        DepartingStationLbl.setVisible(false);
        TrainTypeLbl.setVisible(false);
        LastStopLbl.setVisible(false);
        StationComboBox.setVisible(false);
        trainComboBox.setVisible(false);
        LastStopInput.setVisible(false);
    }
    
    private void updateStationComboBox(ArrayList<String> list){
        StationComboBox.removeAllItems();
        for (String item : list) {
            StationComboBox.addItem(item);
        }
    }
    
    private void updateTrainComboBox(ArrayList<String> list){
        trainComboBox.removeAllItems();
        for (String item : list) {
            trainComboBox.addItem(item);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        LastStopLbl1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        publicTransportLabel = new javax.swing.JLabel();
        trainBtn = new javax.swing.JRadioButton();
        LuasBtn = new javax.swing.JRadioButton();
        BusBtn = new javax.swing.JRadioButton();
        QuestionLbl = new javax.swing.JLabel();
        DepartingStationLbl = new javax.swing.JLabel();
        TrainTypeLbl = new javax.swing.JLabel();
        LastStopLbl = new javax.swing.JLabel();
        StationComboBox = new javax.swing.JComboBox<>();
        trainComboBox = new javax.swing.JComboBox<>();
        LastStopInput = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        CarbonEmisDisplay = new javax.swing.JTextArea();
        homeButton = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        LastStopLbl1.setText("Last Stop:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        publicTransportLabel.setText("Public Transport");

        buttonGroup1.add(trainBtn);
        trainBtn.setText("Train");
        trainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(LuasBtn);
        LuasBtn.setText("Luas");
        LuasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuasBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(BusBtn);
        BusBtn.setText("Bus");
        BusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusBtnActionPerformed(evt);
            }
        });

        QuestionLbl.setText("What mode of transport did you take?");

        DepartingStationLbl.setText("Departing Station:");

        TrainTypeLbl.setText("Train type:");

        LastStopLbl.setText("Last Stop:");

        StationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        StationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StationComboBoxActionPerformed(evt);
            }
        });

        trainComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CarbonEmisDisplay.setColumns(20);
        CarbonEmisDisplay.setRows(5);
        jScrollPane2.setViewportView(CarbonEmisDisplay);

        homeButton.setText("Back to Home");

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(StationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(103, 103, 103)
                                    .addComponent(trainComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(DepartingStationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(92, 92, 92)
                                    .addComponent(TrainTypeLbl))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastStopInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastStopLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(QuestionLbl)
                                .addGap(93, 93, 93))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(publicTransportLabel)
                                .addGap(142, 142, 142)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LuasBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(trainBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(homeButton)
                        .addGap(191, 191, 191))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(trainBtn)
                        .addGap(5, 5, 5)
                        .addComponent(LuasBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BusBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(publicTransportLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuestionLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DepartingStationLbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LastStopLbl)
                        .addComponent(TrainTypeLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trainComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastStopInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(submitBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StationComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_StationComboBoxActionPerformed

    private void trainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainBtnActionPerformed
        // TODO add your handling code here:
        DepartingStationLbl.setVisible(true);
        TrainTypeLbl.setVisible(true);
        LastStopLbl.setVisible(false);
        StationComboBox.setVisible(true);
        trainComboBox.setVisible(true);
        LastStopInput.setVisible(false);
        DepartingStationLbl.setText("Departing station:");
        updateStationComboBox(IR.trainStation);
        TrainTypeLbl.setText("Train type:");
        updateTrainComboBox(IR.trainType);
        LastStopLbl.setText("Last Stop:");
        LastStopInput.setText("");
    }//GEN-LAST:event_trainBtnActionPerformed

    private void LuasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuasBtnActionPerformed
        // TODO add your handling code here:
        DepartingStationLbl.setVisible(true);
        TrainTypeLbl.setVisible(true);
        LastStopLbl.setVisible(true);
        StationComboBox.setVisible(true);
        trainComboBox.setVisible(true);
        LastStopInput.setVisible(true);
        DepartingStationLbl.setText("First Stop:");
        updateStationComboBox(L.firstStop);
        TrainTypeLbl.setText("Last Stop:");
        updateTrainComboBox(L.lastStop);
        LastStopLbl.setText("Luas Line:");
        LastStopInput.setText("");
    }//GEN-LAST:event_LuasBtnActionPerformed

    private void BusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusBtnActionPerformed
        // TODO add your handling code here:
        // Change the contents of the labels, combo boxes, etc
        DepartingStationLbl.setVisible(false);
        TrainTypeLbl.setVisible(true);
        LastStopLbl.setVisible(false);
        StationComboBox.setVisible(false);
        trainComboBox.setVisible(true);
        LastStopInput.setVisible(false);
        DepartingStationLbl.setText("");
        TrainTypeLbl.setText("Bus Type:");
        updateTrainComboBox(B.busType);
        LastStopLbl.setText("");
        LastStopInput.setText("");
    }//GEN-LAST:event_BusBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        if (LastStopInput.isVisible()){
            L.setLuasLine(LastStopInput.getText());
            CarbonEmisDisplay.setText("By taking the Luas, you had no carbon emissions! This is because the Luas is a fully electric service. Happy travelling!");
        } else if (!DepartingStationLbl.isVisible()){
            String busType = (String) trainComboBox.getSelectedItem();
            B.setUserSelectBus(busType);
            B.calcCarbonEmis();
            if (busType.equals("Electric")) {
                CarbonEmisDisplay.setText("You took one of TFI's emission free buses! These buses are fully electric, and therefore there are no carbon emissions! Safe journeys!");
            } else if (busType.equals("Hybrid")) {
                CarbonEmisDisplay.setText("You took one of TFI's hybrid buses! These buses produce 50% less co2 then a disel bus, estimated to be around " +B.getBusHCarbon()+ " metric tons per year on average. A car produces as estimated " +B.getCarCarbon()+ " metric tons of co2 per year. Safe journeys!");
            } else {
                CarbonEmisDisplay.setText("You took one of TFI's diesel buses! There buses produce less co2 than a car, so it's certi=ainly a step in the right direction! These buses produce " +B.getBusDCarbon()+ " metric tons of co2 per year on average. A car produces " +B.getCarCarbon()+ " per year on average. Safe journeys!");
            }
        } else {
            IR.calcCarbonEmis();
            String trainType = (String) trainComboBox.getSelectedItem();
            if (trainType.equals("Intercity")) {
                CarbonEmisDisplay.setText("Irish Rails' Intercity and Commuter trains produce 77% less co2 than a car, according to their adverts. By taking the intercity, you greatly reduced your carbon emissions, as the train produces " +IR.getTrainCarbon()+ " per year on average, while a car produces " +IR.getCarCarbon()+ " metric tons of carbon per year on average. Have fun travelling!");
            } else if (trainType.equals("Commuter")){
                CarbonEmisDisplay.setText("Irish Rails' Intercity and Commuter trains produce 77% less co2 than a car, according to their adverts. By taking the commuter, you greatly reduced your carbon emissions, as the train produces " +IR.getTrainCarbon()+ " per year on average, while a car produces " +IR.getCarCarbon()+ " metric tons of carbon per year on average. Have fun travelling!");
            } else {
                CarbonEmisDisplay.setText("Irish Rails' DART trains are completely electric! Therefore, they don't produce any co2, just like the Luas. Have fun travelling!");
            }
        }
    }//GEN-LAST:event_submitBtnActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SustainabilityGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BusBtn;
    private javax.swing.JTextArea CarbonEmisDisplay;
    private javax.swing.JLabel DepartingStationLbl;
    private javax.swing.JTextField LastStopInput;
    private javax.swing.JLabel LastStopLbl;
    private javax.swing.JLabel LastStopLbl1;
    private javax.swing.JRadioButton LuasBtn;
    private javax.swing.JLabel QuestionLbl;
    private javax.swing.JComboBox<String> StationComboBox;
    private javax.swing.JLabel TrainTypeLbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton homeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel publicTransportLabel;
    private javax.swing.JButton submitBtn;
    private javax.swing.JRadioButton trainBtn;
    private javax.swing.JComboBox<String> trainComboBox;
    // End of variables declaration//GEN-END:variables
}
