/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sustainability;

/**
 *
 * @author wikto
 */
import java.util.ArrayList;

public class SustainabilityGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SustainabilityGUI.class.getName());
    BusService B = new BusService();
    IrishRail IR = new IrishRail();
    Luas L = new Luas();
    protected String userEmis;
    

    /**
     * Creates new form SustainabilityGUI
     */
    public SustainabilityGUI() {
        initComponents();
        DepartingStationLbl.setVisible(false);
        TrainTypeLbl.setVisible(false);
        LastStopLbl.setVisible(false);
        StationComboBox.setVisible(false);
        trainComboBox.setVisible(false);
        LastStopInput.setVisible(false);
        
    }
    
    private void updateStationComboBox(ArrayList<String> list){
        StationComboBox.removeAllItems();
        for (String item : list) {
            StationComboBox.addItem(item);
        }
    }
    
    private void updateTrainComboBox(ArrayList<String> list){
        trainComboBox.removeAllItems();
        for (String item : list) {
            trainComboBox.addItem(item);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        LastStopLbl1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        publicTransportLabel = new javax.swing.JLabel();
        trainBtn = new javax.swing.JRadioButton();
        LuasBtn = new javax.swing.JRadioButton();
        BusBtn = new javax.swing.JRadioButton();
        QuestionLbl = new javax.swing.JLabel();
        DepartingStationLbl = new javax.swing.JLabel();
        TrainTypeLbl = new javax.swing.JLabel();
        LastStopLbl = new javax.swing.JLabel();
        StationComboBox = new javax.swing.JComboBox<>();
        trainComboBox = new javax.swing.JComboBox<>();
        LastStopInput = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        CarbonEmisDisplay = new javax.swing.JTextArea();
        homeButton = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        LastStopLbl1.setText("Last Stop:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.darkGray);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        publicTransportLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        publicTransportLabel.setText("Public Transport");
        getContentPane().add(publicTransportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 6, -1, -1));

        buttonGroup1.add(trainBtn);
        trainBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        trainBtn.setForeground(new java.awt.Color(49, 255, 88));
        trainBtn.setText("Train");
        trainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainBtnActionPerformed(evt);
            }
        });
        getContentPane().add(trainBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 60, 20));

        buttonGroup1.add(LuasBtn);
        LuasBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        LuasBtn.setForeground(new java.awt.Color(49, 255, 88));
        LuasBtn.setText("Luas");
        LuasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuasBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LuasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 60, 20));

        buttonGroup1.add(BusBtn);
        BusBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BusBtn.setForeground(new java.awt.Color(49, 255, 88));
        BusBtn.setText("Bus");
        BusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 60, 20));

        QuestionLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        QuestionLbl.setText("What mode of transport did you take?");
        getContentPane().add(QuestionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 28, -1, -1));

        DepartingStationLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        DepartingStationLbl.setText("Departing Station:");
        getContentPane().add(DepartingStationLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, -1));

        TrainTypeLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        TrainTypeLbl.setText("Train type:");
        getContentPane().add(TrainTypeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 70, -1));

        LastStopLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        LastStopLbl.setText("Last Stop:");
        getContentPane().add(LastStopLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 70, 20));

        StationComboBox.setBackground(new java.awt.Color(49, 255, 88));
        StationComboBox.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        StationComboBox.setForeground(new java.awt.Color(20, 102, 35));
        StationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        StationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StationComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(StationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 108, -1, -1));

        trainComboBox.setBackground(new java.awt.Color(49, 255, 88));
        trainComboBox.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        trainComboBox.setForeground(new java.awt.Color(20, 102, 35));
        trainComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        trainComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(trainComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 108, -1, -1));

        LastStopInput.setBackground(new java.awt.Color(49, 255, 88));
        LastStopInput.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        LastStopInput.setForeground(new java.awt.Color(20, 102, 35));
        LastStopInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastStopInputActionPerformed(evt);
            }
        });
        getContentPane().add(LastStopInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 108, 75, -1));

        CarbonEmisDisplay.setEditable(false);
        CarbonEmisDisplay.setColumns(20);
        CarbonEmisDisplay.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        CarbonEmisDisplay.setForeground(new java.awt.Color(20, 102, 35));
        CarbonEmisDisplay.setLineWrap(true);
        CarbonEmisDisplay.setRows(5);
        CarbonEmisDisplay.setCaretColor(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(CarbonEmisDisplay);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 470, 60));

        homeButton.setBackground(new java.awt.Color(49, 255, 88));
        homeButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        homeButton.setForeground(new java.awt.Color(20, 102, 35));
        homeButton.setText("Back to Home");
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 267, -1, -1));

        submitBtn.setBackground(new java.awt.Color(49, 255, 88));
        submitBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(20, 102, 35));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StationComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_StationComboBoxActionPerformed

    private void trainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainBtnActionPerformed
        // TODO add your handling code here:
        DepartingStationLbl.setVisible(true);
        TrainTypeLbl.setVisible(true);
        LastStopLbl.setVisible(false);
        StationComboBox.setVisible(true);
        trainComboBox.setVisible(true);
        LastStopInput.setVisible(false);
        DepartingStationLbl.setText("Departing station:");
        updateStationComboBox(IR.trainStation);
        TrainTypeLbl.setText("Train type:");
        updateTrainComboBox(IR.trainType);
        LastStopLbl.setText("Last Stop:");
        LastStopInput.setText("");
    }//GEN-LAST:event_trainBtnActionPerformed

    private void LuasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuasBtnActionPerformed
        // TODO add your handling code here:
        DepartingStationLbl.setVisible(true);
        TrainTypeLbl.setVisible(true);
        LastStopLbl.setVisible(true);
        StationComboBox.setVisible(true);
        trainComboBox.setVisible(true);
        LastStopInput.setVisible(true);
        DepartingStationLbl.setText("First Stop:");
        updateStationComboBox(L.firstStop);
        TrainTypeLbl.setText("Last Stop:");
        updateTrainComboBox(L.lastStop);
        LastStopLbl.setText("Luas Line:");
        LastStopInput.setText("");
    }//GEN-LAST:event_LuasBtnActionPerformed

    private void BusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusBtnActionPerformed
        // TODO add your handling code here:
        // Change the contents of the labels, combo boxes, etc
        DepartingStationLbl.setVisible(false);
        TrainTypeLbl.setVisible(true);
        LastStopLbl.setVisible(false);
        StationComboBox.setVisible(false);
        trainComboBox.setVisible(true);
        LastStopInput.setVisible(false);
        DepartingStationLbl.setText("");
        TrainTypeLbl.setText("Bus Type:");
        updateTrainComboBox(B.busType);
        LastStopLbl.setText("");
        LastStopInput.setText("");
    }//GEN-LAST:event_BusBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        if (LastStopInput.isVisible()){
            L.setLuasLine(LastStopInput.getText());
            CarbonEmisDisplay.setText("By taking the Luas, you had no carbon emissions! This is because the Luas is a fully electric service. Happy travelling!");
        } else if (!DepartingStationLbl.isVisible()){
            String busType = (String) trainComboBox.getSelectedItem();
            B.setUserSelectBus(busType);
            B.calcCarbonEmis();
            if (busType.equals("Electric")) {
                CarbonEmisDisplay.setText("You took one of TFI's emission free buses! These buses are fully electric, and therefore there are no carbon emissions! Safe journeys!");
            } else if (busType.equals("Hybrid")) {
                CarbonEmisDisplay.setText("You took one of TFI's hybrid buses! These buses produce 50% less co2 then a disel bus, estimated to be around " +B.getBusHCarbon()+ " metric tons per year on average. A car produces as estimated " +B.getCarCarbon()+ " metric tons of co2 per year. Safe journeys!");
            } else {
                CarbonEmisDisplay.setText("You took one of TFI's diesel buses! There buses produce less co2 than a car, so it's certainly a step in the right direction! These buses produce " +B.getBusDCarbon()+ " metric tons of co2 per year on average. A car produces " +B.getCarCarbon()+ " per year on average. Safe journeys!");
            }
        } else {
            IR.calcCarbonEmis();
            String trainType = (String) trainComboBox.getSelectedItem();
            if (trainType.equals("Intercity")) {
                CarbonEmisDisplay.setText("Irish Rails' Intercity and Commuter trains produce 77% less co2 than a car, according to their adverts. By taking the intercity, you greatly reduced your carbon emissions, as the train produces " +IR.getTrainCarbon()+ " per year on average, while a car produces " +IR.getCarCarbon()+ " metric tons of carbon per year on average. Have fun travelling!");
            } else if (trainType.equals("Commuter")){
                CarbonEmisDisplay.setText("Irish Rails' Intercity and Commuter trains produce 77% less co2 than a car, according to their adverts. By taking the commuter, you greatly reduced your carbon emissions, as the train produces " +IR.getTrainCarbon()+ " per year on average, while a car produces " +IR.getCarCarbon()+ " metric tons of carbon per year on average. Have fun travelling!");
            } else {
                CarbonEmisDisplay.setText("Irish Rails' DART trains are completely electric! Therefore, they don't produce any co2, just like the Luas. Have fun travelling!");
            }
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void trainComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainComboBoxActionPerformed

    private void LastStopInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastStopInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastStopInputActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SustainabilityGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BusBtn;
    private javax.swing.JTextArea CarbonEmisDisplay;
    private javax.swing.JLabel DepartingStationLbl;
    private javax.swing.JTextField LastStopInput;
    private javax.swing.JLabel LastStopLbl;
    private javax.swing.JLabel LastStopLbl1;
    private javax.swing.JRadioButton LuasBtn;
    private javax.swing.JLabel QuestionLbl;
    private javax.swing.JComboBox<String> StationComboBox;
    private javax.swing.JLabel TrainTypeLbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton homeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel publicTransportLabel;
    private javax.swing.JButton submitBtn;
    private javax.swing.JRadioButton trainBtn;
    private javax.swing.JComboBox<String> trainComboBox;
    // End of variables declaration//GEN-END:variables
}
